apiVersion: batch/v1
kind: Job
metadata:
  name: pandas-to-bq-basic3
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      containers:
      - name: pandas-to-bq-basic3
        image: europe-west1-docker.pkg.dev/pod-fr-retail/demok8/demo_k8_jobs_basic
        command: ["python3",  "/pandas_to_bq.py"]
        resources:
            requests:
                memory: "10Mi"
                cpu: "100m"
                nvidia.com/gpu: "2"
            limits:
                memory: "10Mi"
                cpu: "100m"
                nvidia.com/gpu: "2"
        env:
        - name: TEST_VARIABLE
          value: "hello new job 2"
      restartPolicy: Never