apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pandas-to-bq-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pandas-to-bq
            image: gcr.io/pod-fr-retail/k8_operators/py_pandas_bq
            command: ["python3",  "/pandas_to_bq.py"]
            resources:
                requests:
                    memory: "64Mi"
                    cpu: "250m"
                limits:
                    memory: "128Mi"
                    cpu: "500m"
            env:
            - name: TEST_VARIABLE
              value: "hello world"
          restartPolicy: Never