# Use the official lightweight Node.js 12 image.
# https://hub.docker.com/_/node
FROM gcr.io/pod-fr-retail/get-reports-details
RUN pip install apache-beam
# Run the web service on container startup.
#CMD [ "node", "index.js" ]